name: WhereIs
version: 2.1.3
main: me.varchar42.whereis.WhereIsPlugin
author: VarChar42 (slightly modified by Stefan456789)
commands:
  whereis:
    usage: /whereis [Player]
  otp:
    usage: /otp [Player] [x] [y] [z]